version: "3.9"

services:
  influxdb:
    image: "quay.io/influxdb/influxdb:v2.0.9"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`whoami.qxf.de`)"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.tls.certresolver=myresolver"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - influxdb_data:/root
    networks:
      db:
        aliases:
          - influxdb
      net:
    # ports:
    #  - "8086:8086"
    environment:
      - TZ=Europe/Berlin

  grafana:
    image: "grafana/grafana:latest"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3002:3000"
    networks:
      - db
      - net
    environment:
      - TZ=Europe/Berlin

  telegraf:
    image: "telegraf"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - telegraf_data:/etc/telegraf/
    networks:
      - db
      - net
    environment:
      - TZ=Europe/Berlin
    
volumes:
  influxdb_data:
  grafana_data:
  telegraf_data:
  
networks:
  db:
  net:
    external:
      name: traefik_net
