version: "3.7"
services:
  influxdb:
    image: "quay.io/influxdb/influxdb:v2.0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      db:
        aliases:
          - influxdb
    ports:
      - "8086:8086"
    environment:
      - TZ=Europe/Berlin

  chronograph:
    image: "chronograf:latest"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - chronograf_data:/var/lib/chronograf
    ports:
      - "3001:8888"
    networks:
      - db
      
  grafana:
    image: "grafana/grafana:latest"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3002:3000"
    networks:
      - db
    environment:
      - TZ=Europe/Berlin


  kapacitor:
    image: "kapacitor:latest"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - kapacitor_data:/var/lib/kapacitor
    ports:
      - "3003:9092"
    networks:
      db:
        aliases:
          - kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086

volumes:
  influxdb_data:
  chronograf_data:
  grafana_data:
  kapacitor_data:
  
networks:
  db:
