version: "3.7"
services:
  influxdb:
    image: "influxdb:latest"
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      db:
        aliases:
          - influxdb

  chronograph:
    image: "chronograf:latest"
    restart: unless-stopped
    volumes:
      - chronograf_data:/var/lib/chronograf
    ports:
      - "3001:8888"
    networks:
      - db
      
  grafana:
    image: "grafana/grafana:latest"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3002:3000"
    networks:
      - db

  kapacitor:
    image: "kapacitor:latest"
    restart: unless-stopped
    volumes:
      - kapacitor_data:/var/lib/kapacitor
    ports:
      - "3003:9092"
    networks:
      db:
        aliases:
          - kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086

volumes:
  influxdb_data:
  chronograf_data:
  grafana_data:
  kapacitor_data:
  
networks:
  db:
